### ISSUE TITLE
Support Sideloading?

### ISSUE THREAD

**Issue by jcarrig** [cloudbees-oss/zendesk-java-client#129]
Zendesk API supports sideloading to avoid unnecessary api calls for certain endpoints (https://developer.zendesk.com/rest_api/docs/core/side_loading#side-loading)...

For example: `.../tickets.json?include=users` would return the tickets and the users data.

Is this currently supported by this library?  Is there any interest to support it?  

Thanks.

**Comment by aheritier** [comment]
Hi @jcarrig 

  AFAIK it's not supported but yes it may be a good addition

Best regards

**Comment by pesca506** [comment]
Any news about this?

Many thanks

**Comment by chuck-wood** [comment]
What would be a preferred idiom? Assuming we have a function `getZendesk()` that returns a built Zendesk obect, would you prefer something like:

```java
getZendesk().sideload("users").getTicket(123);
```

or

```java
getZendesk().getTicket(123, "users");
```

Thanks!

**Comment by aheritier** [comment]
maybe the second one with a String... vararg for the list of strings to include ?
not completely sure. @johnou @stephenc WDYT ?

**Comment by stephenc** [comment]
Wouldn’t it be better to start with the side load and then complete with the request:

`zendesk.withUsers().getTicket(123)`

The implementation *should* be easier as we can have a special “wrapper” object and modify the return types if necessary.

Otherwise I don’t have too strong an option... code talks louder than pseudo code sketches

**Comment by chuck-wood** [comment]
The easiest implementation for any one endpoint would be a single comma-separated string that would just be appended to the URL. Applying that to the whole library would involve a lot of copy pasta and overloading, though, which both seem counter to the established style.

I don't mean to turn this into endless meetings, just doing a quick check before diving in :)

**Comment by dtertman** [comment]
I was looking at this just now, and personally I'd favor a new TicketRequest object, e.g.
```
Long id;
EnumSet<TicketSideloads> sideloads;
```
which you could then feed to a separate ```getTicket```.

**Comment by flyingdutchman** [comment]
Some news about this features ?
