### ISSUE TITLE
"additional_collaborators" is not supported in Ticket Model

### ISSUE THREAD

**Issue by eventd** [cloudbees-oss/zendesk-java-client#155]
Hi, I have a requirement to add external user as CC to ticket notification.
And seen from [Zendesk ticket API doc](https://developer.zendesk.com/rest_api/docs/core/tickets#setting-collaborators), setting "additional_collaborators" field will fit.

But It seems that current Ticket model does not support this.

**Comment by LeeVidor** [comment]
Has the ability to add additional cc emails been added yet? I was unable to find it.
