### ISSUE TITLE
bug: querying with email having + character results in wrong encoded URL

### ISSUE THREAD

**Issue by ali-jawad** [cloudbees-oss/zendesk-java-client#177]
We have a query that looks like this, which fails:

`zendeskClient.getSearchResults(Ticket, "requester:example+email@test.com")`
Or: 
`getTicketsFromSearch("requester:example+email@test.com")`

This results in a query:
`http://company.zendesk.com/api/v2/search.json?query=requester%3Aexample+email%40test.com+type%3Aticket`

which returns zero results whereas we expect it to return something.

For it work really work with Zendesk server and return true results, based on our attempts using cURL, it should ultimately be:
`http://company.zendesk.com/api/v2/search.json?query=requester%3Aexample%2Bemail%40test.com+type%3Aticket`

Where our email's `+` character should get encoded as usual, and the other special character `+` that separates search fields should remain there un-encoded in the final URL.

As an attempt to work around it, we tried encoding the `+` by ourselves before passing it to the method, but that would result in something incorrect too:
`http://company.zendesk.com/api/v2/search.json?query=requester%3Aexample%252Bemail%40test.com+type%3Aticket`

So we do not have a workaround using the Java client library.

**Comment by emercer** [comment]
I also have the same issue :/
