### ISSUE TITLE
View support coming?

### ISSUE THREAD

**Issue by chuck-wood** [cloudbees-oss/zendesk-java-client#197]
Is there currently any intention to support [Views](https://developer.zendesk.com/rest_api/docs/core/views)? I am considering getting started on it but don't want to duplicate work.

**Comment by johnou** [comment]
@chuck-wood not in the short term as far as I am aware, looking forward to the pull request!

**Comment by rcprcp** [comment]
First, I really appreciate the effort which has gone into this library!  It offers a lot of functionality in an easy-to-use way. 

I would like to follow up on this question - I need limited View support - getting a list of the Views, and running a View to get the list of matching Tickets.  Is there any intention of just adding this much View support?  I suspect this would cover a lot of the use cases out there without requiring all the esoteric functionality one sees in the docs for Views.    

Thanks!
