### ISSUE TITLE
bug: wrong URI creation with params

### ISSUE THREAD

**Issue by asafronienkov** [cloudbees-oss/zendesk-java-client#204]
We have a query that looks like this, which fails:

zendeskClient.getSearchResults(Ticket.class, "requester:1111",                                                                 "sort_by=created_at&sort_order=desc&page=1&per_page=11");

This results in a query:
http://company.zendesk.com/api/v2/search.json?query=requester%3A1111%2Btype%3Aticket&params=sort_by%3Dcreated_at%2Bsort_order%3Ddesc%2Bpage%3D1%2Bper_page%3D11

which returns default results with page 100 instead of indicated 11.
so query should be smth like this  
query=type:ticket requester:1111&sort_by=created_at&sort_order=desc&page=2&per_page=11

**Comment by Helmsdown** [comment]
So the implementation of ```org.zendesk.client.v2.Zendesk#getSearchResults(java.lang.Class<T>, java.lang.String, java.lang.String)``` is interesting. Was it intended that "params" be things like sort order? If so, should it have been a string? Or some Map<String, String>?

I need to perform a search and sort the results by updated_at. I'd like to submit a PR to support this and overcome the ```// TODO search with sort order``` comment in Zendesk.java 

Could a repo owner chime in here?
