### ISSUE TITLE
Make CustomFieldValue abstract and create concrete objects

### ISSUE THREAD

**Issue by russellhoff** [cloudbees-oss/zendesk-java-client#241]
I updated to the latest version and found that CustomFieldValue's value has changed from String to String[].

This is a major update and I guess not strictly necessary. 

Zendesk added the MultiSelect field, but the rest are single valued fields. 

In my opìnion, CustomFieldValue class should be abstract. Then there should be concrete classes for each custom field [type](https://support.zendesk.com/hc/en-us/articles/203661866-About-custom-field-types): DropDown, MultiSelect, Text, MultiLineText, and so on.

I'd be able to help if somebody assists me on how to accomplish this task.

**Comment by aheritier** [comment]
I agree @russellhoff it is not perfect but it was the easiest to be compatible with the new type
We can probably use custom (de)serialisers based on the typebut we'll have to take care that each time that they'll add a new type it won't be supported by default (or worst it will break the integration like the problem we had here with the introduction of MultiSelect fields

https://github.com/FasterXML/jackson-docs/wiki/JacksonPolymorphicDeserialization
http://www.baeldung.com/jackson-inheritance

**Comment by russellhoff** [comment]
I understand @aheritier. Additionally testing thing on Zendesk is a hard thing. I'll keep you informed

**Comment by aheritier** [comment]
yes @russellhoff We are asking for years to @zendesk to provide us a test instance with all possible options to have a real test environment and ... no response / help :(

For now we are using our sandbox from CloudBees  with all risks it has ...

**Comment by russellhoff** [comment]
We're aware of that issue, and whenever we make changes to our web services we must be really cautious... Anyway, depending on your Zendesk license a sandbox may be available for testing purposes.

**Comment by aheritier** [comment]
yes we use our sandbox. But it used for various purposes and not only to test this integration thus we can easily break our testcases and it is hard to maintain a dataset to use in our integration tests
