### ISSUE TITLE
 running throw java.lang.NoClassDefFoundError 

### ISSUE THREAD

**Issue by yongshengdev** [cloudbees-oss/zendesk-java-client#291]
hi, i add `implementation group: 'com.cloudbees.thirdparty', name: 'zendesk-java-client', version: '0.9.0'` in build.gradle.
when running throw java.lang.NoClassDefFoundError org.asynchttpclient.config.-$$Lambda$AsyncHttpClientConfigHelper$Config$i2FemBXcTsp4XC8TeGzgqQ02f_U 
but i find it's exist in External Libraries. build success but why cause throw error when running ? 
thx for advance.

**Comment by aheritier** [comment]
I'm not a gradle expert @SilenceBurst but I see 2 possibilities:
* Transitive dependencies aren't correctly interpreted
* You have a conflic with another library using asynchttpclient and thus you get on your classpath the wrong version and this class doesn't exist

**Comment by SilenceBurst** [comment]
I create a new project implementation this library, also throw this error, I guess it not because conflict with another library. Let me check it again.
