### ISSUE TITLE
Add support for User Segments / Permissions Groups

### ISSUE THREAD

**Issue by Dohbedoh** [cloudbees-oss/zendesk-java-client#292]
**Is your feature request related to a problem? Please describe.**

I cannot manage [User Segments](https://developer.zendesk.com/rest_api/docs/help_center/user_segments) / [Permissions](https://developer.zendesk.com/rest_api/docs/help_center/permission_groups) with the java client.

**Describe the solution you'd like**

An API to manage User Segments and Permissions Groups.

**Describe alternatives you've considered**

`curl` / `wget`

**Comment by aheritier** [comment]
@Dohbedoh can you verify if #316 is properly fixing this issue please ?
