### ISSUE TITLE
Change Zendesk constructors from private to protected

### ISSUE THREAD

**Issue by regbo** [cloudbees-oss/zendesk-java-client#306]
**Is your feature request related to a problem? Please describe.**
Right now all Zendesk constructors are private, preventing sub-classing of the client. A custom sub-class would allow tweaks to the client, as well as new convenience methods.

**Describe the solution you'd like**
Change the constructor to protected

**Describe alternatives you've considered**
Currently I create a delegate wrapper of Zendesk

**Comment by aheritier** [comment]
@regbo if you are extending the class (right now with a delegate), couldn't it make sense to improve the code here instead ?

**Comment by regbo** [comment]
Hi @aheritier, here's an example. The new Zendesk API has an additional field called "email_ccs". I added support for it by extending the Ticket class as so:

`
public class TicketV2 extends Ticket {

	@SerializedName("email_ccs")
	private List<TicketUser> emailCcs;

	@SerializedName("followers")
	private List<TicketUser> followers;

	@SerializedName("follower_ids")
	private List<Long> followerIds;

	@SerializedName("email_cc_ids")
	private List<Long> emailCcIds;

	@SerializedName("additional_collaborators")
	private List<? extends Object> additionalCollaborators;

	@SerializedName("metric_set")
	private MetricSet metricSet;
`

Then, to make coding easier, I added a method to zendesk.java that returned TicketV2 instead of Ticket. This is just an example of why having a protected constructor helps.

I think a permanent change would help when users want to make small custom changes to the client.

**Comment by aheritier** [comment]
I am really annoyed. I understand very well the need to hack/extend the library to implement something not yet available in it (especially because our "community" isn't really (re)active).
On the other side I am afraid that it could reduce the number of contributions and we add more constraints to maintain the compatibility of the class.
