### ISSUE TITLE
Missing metadata on Ticket Object

### ISSUE THREAD

**Issue by MadsFox** [cloudbees-oss/zendesk-java-client#326]
Have tried to add metadata to a zendesk ticket, but is not supported by this library as fare as i can see. 

Miss a ticket.setMetadata(Metadata metadata) method to add metadata to a Zendesk Ticket

Going to write a pull request and before then extend the Ticket class with the fix locally

Metadata info from Zendesk API: 
https://developer.zendesk.com/rest_api/docs/support/tickets#setting-metadata

**Comment by aheritier** [comment]
yes we should add a Map to store the metadata
