### ISSUE TITLE
Zendesk.getSearchResult(Ticket.class, "email+with+plus+sign@email.com") giving no Tickets in result.

### ISSUE THREAD

**Issue by vkvashistha** [cloudbees-oss/zendesk-java-client#371]
**Describe the bug**
Zendesk.getSearchResult(Ticket.class, "email+with+plus+sign@email.com") giving no Tickets in result. Thought tickets for this email exists.

**To Reproduce**
        Iterable<SearchResultEntity> tickets = zd.getSearchResults(Ticket.class, "email+with+plus+sign@email.com");
        System.out.println("Tickets search completed");
        int count = 0;
        for(SearchResultEntity result : tickets) {
            System.out.println("SearchResult found");
            if(result instanceof Ticket) {
                Ticket ticket = (Ticket)result;
                System.out.println("Ticket : " + (count++) + ticket.getSubject());
//            zd.deleteTicket(ticket);
            }
          System.out.println("Total Tickets : " + count);  // Returning 0, expected 1
        }

**Expected behavior**
zd.getSearchResults() should return 1 ticket in result. As I've one ticket in Zendesk which belongs to  "email+with+plus+sign@email.com".
But when I put email address having no + sign, it's working fine.

I'm using version 0.14.0

**Comment by PierreBtz** [comment]
@aheritier could this be related to the other issue we observed with the `+` the other day for authentication? `+` wouldn't be well handled?

**Comment by aheritier** [comment]
@PierreBtz it's possible, it was also related to the usage of `+` in the email used for the authentication.
But I don't know if the issue was at the API level or in the script injecting the credentials
I think the problem reported here could be easy to (in)validate with a new Integration test
