### ISSUE TITLE
Support for sort_by abd sort_order in search API

### ISSUE THREAD

**Issue by AdityaMishra95** [cloudbees-oss/zendesk-java-client#389]
Is the Support for sort_by abd sort_order in search API released till now?

`public Iterable<Ticket> getTicketsFromSearch(String searchTerm) {
        return new PagedIterable<>(tmpl("/search.json{?query}").set("query", searchTerm + "+type:ticket"),
                handleList(Ticket.class, "results"));
    }`

because i don't see it yet. Is there any other way of achieving this?

**Comment by aheritier** [comment]
Aren't you looking for 
https://github.com/cloudbees-oss/zendesk-java-client/blob/master/src/main/java/org/zendesk/client/v2/Zendesk.java#L1712-L1718

```
    public <T extends SearchResultEntity> Iterable<T> getSearchResults(Class<T> type, String query, String sortBy, SortOrder sortOrder) {
        Map<String, Object> paramsMap = new HashMap<>(2);
        paramsMap.put("sort_by", sortBy);
        paramsMap.put("sort_order", sortOrder.getQueryParameter());

        return getSearchResults(type, query, paramsMap);
    }
```

**Comment by jemishmoradiya** [comment]
> Aren't you looking for
> https://github.com/cloudbees-oss/zendesk-java-client/blob/master/src/main/java/org/zendesk/client/v2/Zendesk.java#L1712-L1718
> 
> ```
>     public <T extends SearchResultEntity> Iterable<T> getSearchResults(Class<T> type, String query, String sortBy, SortOrder sortOrder) {
>         Map<String, Object> paramsMap = new HashMap<>(2);
>         paramsMap.put("sort_by", sortBy);
>         paramsMap.put("sort_order", sortOrder.getQueryParameter());
> 
>         return getSearchResults(type, query, paramsMap);
>     }
> ```

This isn't working from zendesk API end.. Support for sort_by abd sort_order is working in "/users/{userId}/tickets/requested.json" curl URL. but here https://github.com/cloudbees-oss/zendesk-java-client/blob/master/src/main/java/org/zendesk/client/v2/Zendesk.java#L492-L495 only one method available.. need this method with query, params
