### ISSUE TITLE
Add Options to UserField class

### ISSUE THREAD

**Issue by russellhoff** [cloudbees-oss/zendesk-java-client#445]
**Is your feature request related to a problem? Please describe.**
As Zendesk's documentation says [here](https://developer.zendesk.com/api-reference/ticketing/users/user_fields/), UserField class does contain a `custom_field_options` attribute, like Field class. This attribute does contain each Option value when the type of UserField is of type dropdown.

**Describe the solution you'd like**
I would add an attribute to the UserField class, containing a List of Option... Something like the following:

```java
@Data
@EqualsAndHashCode(callSuper = true)
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class DropdownUserField extends UserField {

	private static final long serialVersionUID = 8871506778976711701L;

	@JsonProperty("custom_field_options") @Builder.Default private List<Option> customFieldOptions = new ArrayList<>();
	
	public Boolean addOption(Option pOption) {
		if(customFieldOptions.contains(pOption))
			return false;
		return customFieldOptions.add(pOption);
	}
	
	public Boolean hasOption(Option pOption) {
		return customFieldOptions.contains(pOption);
	}
	
	public Boolean removeOption(Option pOption) {
		if(!customFieldOptions.contains(pOption))
			return false;
		return customFieldOptions.remove(pOption);
	}
	
}
```

**Describe alternatives you've considered**
Perhaps, a new Option class should be created, as an inner class within UserField. I do not know which alternative fits better, but this should be supported.

**Additional context**
Nothing else.

**Comment by PierreBtz** [comment]
Issue got stalled so the bot closed it. That doesn't mean we are not interested by a PR :)
