### ISSUE TITLE
Implementation of /api/v2/users/update_many.json

### ISSUE THREAD

**Issue by unsync** [cloudbees-oss/zendesk-java-client#47]
Hi,
Great job with this API, but there's no implementation of the /api/v2/users/update_many.json method.

This is greatly usefull to update a batch of users. Updating a batch of users one by one require a lot of thread to be opened.

Thanks in advance

**Comment by wakingrufus** [comment]
I have opened a PR for this

**Comment by wakingrufus** [comment]
My PR is here: https://github.com/cloudbees/zendesk-java-client/pull/260
my new test passed when I ran the tests locally. I am not sure why ci is failing so many tests....

**Comment by any1one** [comment]
Hi !
My initial request was for the /users/update_many.json not /tickets/update_many.json, but thanks for your work ;)

**Comment by wakingrufus** [comment]
oops! I will open a separate ticket for that. Sorry for the confusion!

**Comment by wakingrufus** [comment]
@any1one Once I get update tickets merged, I will come back and see if I can implement this as well.
