### ISSUE TITLE
getSearchResult() returns only 100 results

### ISSUE THREAD

**Issue by SNitzansh** [cloudbees-oss/zendesk-java-client#489]
Hello, I'm entering a query to getSearchResult() function but I get just 100 entities when there is a 400. Maybe I don't understand how to use paging but I think it's should be automatic. I would like to get some help... Thanks!
EDIT:
I think it's read in the wrong way the responseNode. It gets only the values and can't read the next_page field, which causes this iterator to stop after only 100 results and can't move to the next page.

**Comment by PierreBtz** [comment]
@SNitzansh 

> Maybe I don't understand how to use paging but I think it's should be automatic. 

Unsure what you call "automatic paging". The `getSearchResult` method should return an iterable that will handle the query of subsequent pages for you. Can you please send a snippet of code or better a self contained unit test?

**Comment by PierreBtz** [comment]
@SNitzansh I'm closing since it seems more like a question than an actual bug report.
Feel free to open a discussion in https://github.com/cloudbees-oss/zendesk-java-client/discussions in case you have further questions on how to use pagination.
