### ISSUE TITLE
zendesk-java-client 0.18.0 release is out

### ISSUE THREAD

**Issue by evlyngeorge** [cloudbees-oss/zendesk-java-client#502]
### Discussed in https://github.com/cloudbees-oss/zendesk-java-client/discussions/492

<div type='discussions-op-text'>

* Hi @PierreBtz @rcprcp  Can you please include this api in incremental export. This include Parameter is not accepted by the existing api's. We need this for our project.
https://{subdomain}.zendesk.com/api/v2/incremental/tickets.json?start_time=1332034771&include=metric_sets

**Comment by PierreBtz** [comment]
I'm afraid I don't have the bandwidth to work on this currently, but I'll happily take a PR.

**Comment by evlyngeorge** [comment]
Can i make changes to this repo for the same and commit it ?

**Comment by PierreBtz** [comment]
You can provide a Pull Request with the new feature and some tests.
