### ISSUE TITLE
Enable search for users by external_id where external_id is a String (not a long)

### ISSUE THREAD

**Issue by andy-may-at** [cloudbees-oss/zendesk-java-client#548]
The method to retrieve users by external ID: (`public List<User> getUsersByExternalIds(long externalId, long... externalIds)`) expects the external IDs to be `long`s, but the underlying value is a `String` in the Zendesk API 

In my use case, our external IDs are Strings, so we can't search for users by external ID using this method,..

I propose to implementing an additional `public List<User> getUsersByExternalIds(String externalId, String... externalIds)` method which 

I'll look to raise a PR for this shortly if the change would be welcomed

**Comment by PierreBtz** [comment]
@andy-may-at indeed that doesn't seem correct. PR welcome, you can also deprecate the old method taking longs for future removal.

**Comment by colbya** [comment]
Is there history on why the api often does varargs with the double parameters?

**Comment by andy-may-at** [comment]
I assumed that it was a way of allowing `1...N` parameters, rather than `0...N`

**Comment by colbya** [comment]
Is it worth considering making the idArray method generic and using it for the previous Long and the new String case?

```
    private static <R> List<R> idArray(R id, R... ids) {
        List<R> result = new ArrayList<>(ids.length + 1);
        result.add(id);
        for (R i : ids) {
            result.add(i);
        }
        return result;
    }
```

**Comment by andy-may-at** [comment]
@colbya
That sounds good, but has some complications:

If we do that, but keep the signature of `getUsersByExternalIds(long, long...)`, then it looks like we would have to convert it's vararg long[] into an Long[] before calling `idArray()`

And if we change the signature to `getUsersByExternalIds(Long, Long...)` then there's a risk that we break any calling code that was relying on Java doing type promotion. 
(i.e. anything calling `getusersByExternalIds(1,2,3)` would no longer compile & would have to be replaced with `getusersByExternalIds(1L, 2L, 3L)`
