### ISSUE TITLE
Switch to cursor based pagination for Users

### ISSUE THREAD

**Issue by colbya** [cloudbees-oss/zendesk-java-client#555]
**Is your feature request related to a problem? Please describe.**
Zendesk is encouraging usage of the newer cursor based pagination especially for large result sets. We recently ran into issues with the older offset based pagination with frequent changes to our user set. The offset based pagination bases the paging off of a cached total count of users. In our case that count was being cached for 24 hours which prevent seeing additional new pages added to the user collection. A similar problem exists if a large number of users are deleted, the paging will continue to instruct you to page through empty pages until the paging matches the cached user count.

**Describe the solution you'd like**
Offset pagination is the default and cursor based pagination can be enabled by adding a `?page[size]=100` parameter to the request. The returned paging information is similar but located in a different JSON object. Support for both offset and cursor based pagination can be added by looking for the cursor based pagination first and then falling through to the existing offset based pagination.

Cursor based pagination can then be incrementally added to specific calls in this library as needed.

**Describe alternatives you've considered**
Zendesk was contacted about documenting or fixing the page count that is cached for ~24 hours and they recommended switching to cursor based pagination.

Alternatively, the paging navigation links could be ignored and paging offsets continue, even if a next link is null, until an empty page is fetched. In the case of the cached count affecting offset paging, the non-navigable pages do exist even though they never appear in the paging navigation.

PR to be submitted with a change to just the getUsers() endpoint, other endpoints could benefit from this change but are not covered by the PR

**Additional Reference**

https://developer.zendesk.com/api-reference/introduction/pagination/

https://developer.zendesk.com/documentation/api-basics/pagination/paginating-through-lists-using-cursor-pagination/

Cursor pagination includes a links and meta section in the response with an opaque cursor value that is be included to fetch the next page.

```
"meta": {
    "has_more": true,
    "after_cursor": "xxx",
    "before_cursor": "yyy"
},
"links": {
    "next": "https://example.zendesk.com/api/v2/tickets.json?page[size]=100&page[after]=xxx",
    "prev": "https://example.zendesk.com/api/v2/tickets.json?page[size]=100&page[before]=yyy"
}
```

https://developer.zendesk.com/documentation/api-basics/pagination/paginating-through-lists-using-offset-pagination/

Offset pagination includes a next_page link in the top level of the JSON response with a integer page value that returns values that start at an offset multiple from the beginning of the collection.

```
"tickets": [ ... ],
"next_page": "https://example.zendesk.com/api/v2/tickets.json?page=2",
```

**Comment by andy-may-at** [comment]
Frustratingly, the Zendesk APIs seem inconsistent in their implementation of cursor based pagination.
e.g. the content_tags resource (https://developer.zendesk.com/api-reference/help_center/help-center-api/content_tags/#search-content-tags) has a `meta` section in the response, but no `links` section

e.g. 
```
{
    "records": [
        {
            "id": "1234567890ABCDEFGHIJKLMNOP",
            "name": "A tag",
            "created_at": "2023-01-20T13:50:12.000Z",
            "updated_at": "2023-01-20T13:50:12.000Z"
        }
    ],
    "meta": {
        "has_more": true,
        "after_cursor": "ABCD",
        "before_cursor": "EFGH"
    }
}
```

So if we wanted to take a more generalised approach to supporting cursor pagination, we'd have to know which resources support which variant(s)

**Comment by PierreBtz** [comment]
@andy-may-at what you describe looks like a bug since the general concept of cursor pagination is documented (https://developer.zendesk.com/api-reference/introduction/pagination/#using-cursor-pagination) and references a link session.

**Comment by andy-may-at** [comment]
I can raise that bug with Zendesk.
We're fairly new users of ZD, so I've got no idea how quickly they turn around bug reports in the API

**Comment by colbya** [comment]
PR #565 adds cursor pagination to the getUsersByRole method.
