### ISSUE TITLE
Bulk Delete Tickets should return JobStatus

### ISSUE THREAD

**Issue by raymondpressly** [cloudbees-oss/zendesk-java-client#592]
**Is your feature request related to a problem? Please describe.**

The Zendesk API Documentation for [Bulk Delete Tickets](https://developer.zendesk.com/api-reference/ticketing/tickets/tickets/#bulk-delete-tickets) specifies a JobStatus is returned.

The problem is that the method signature in the client does not match:

https://github.com/cloudbees-oss/zendesk-java-client/blob/e609033b5a2c8501a8d0f7b13f40e2f075e74ddc/src/main/java/org/zendesk/client/v2/Zendesk.java#L440-L443

**Describe the solution you'd like**

The method should return a JobStatus so that the caller can follow along with how the job progresses:

```java
    public JobStatus deleteTickets(long id, long... ids) {
        complete(submit(req("DELETE", tmpl("/tickets/destroy_many.json{?ids}").set("ids", idArray(id, ids))),
                handleJobStatus()));
    }
```

**Describe alternatives you've considered**

Delete tickets 1 by 1. Not an option as we are trying to limit the number of questions we submit.

**Additional context**

N/A

**Comment by PierreBtz** [comment]
Agreed, that would be a nice enhancement, pull request welcome!

**Comment by syedaffanhamdani** [comment]
Created a pull request for it. :)
