### ISSUE TITLE
add support for Jira Links API call

### ISSUE THREAD

**Issue by timveil** [cloudbees-oss/zendesk-java-client#663]
tracking ticket to add support for Jira Links API call as described here... https://developer.zendesk.com/api-reference/ticketing/jira/links/

**Comment by timveil** [comment]
@PierreBtz  or @duemir any chance ya'll could cut a release with this PR?

**Comment by PierreBtz** [comment]
Sorry, it totally sliped my mind there was an unreleased change in this project, I'll cut a release.

**Comment by PierreBtz** [comment]
@timveil https://github.com/cloudbees-oss/zendesk-java-client/releases/tag/zendesk-java-client-0.24.3
