### ISSUE TITLE
Add TpeVoiceComment to CommentType enum

### ISSUE THREAD

**Issue by diendanyoi54** [cloudbees-oss/zendesk-java-client#691]
I recently attempted to upgrade our Java client from _0.13.0_ to **0.25.0** because of the _Cursor-based pagination_ update on **May 20, 2024** but after making the switch, errors occurred when **getTicketComments** was called. We have comments that implement _Talk Partner Edition_ which saves the comment type as **TpeVoiceComment** but the Comment object's type field of **CommentType** only has _VoiceComment_ and _Comment_ available so when deserializing the comment it throws an error.

```kotlin
package org.zendesk.client.v2.model;

public enum CommentType {
    COMMENT("Comment"),
    VOICE_COMMENT("VoiceComment");

    private final String name;

    private CommentType(String name) {
        this.name = name;
    }

    public String toString() {
        return this.name;
    }
}
```

1. Create a comment either with the API or in the GUI with type TpeVoiceComment
2. Retrieve comment with the Cloudbees Java client using the **getTicketComments** method
3. See the error:
```
org.zendesk.client.v2.ZendeskException: java.lang.IllegalArgumentException: Cannot deserialize value of type org.zendesk.client.v2.model.CommentType from String "TpeVoiceComment": not one of the values accepted for Enum class: [VoiceComment, Comment]
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: org.zendesk.client.v2.model.Comment["type"])
```

When Cloudbees **getTicketComments** method is called, the expectation is that it will be able to properly deserialize **TpeVoiceComment** so it will not throw an error and instead properly return the comment.

 - Java Temurin 17.0.10
 - Version 0.25.0

**Comment by PierreBtz** [comment]
@diendanyoi54 sorry for the delay...

I don't have access to the Talk Partner Edition to check about the specifics, so I simply added the missing field value in the enum (https://github.com/cloudbees-oss/zendesk-java-client/pull/702). That would fix the issue you reported BUT I have no way to check if this is enough.
Can you please test and report?

**Comment by diendanyoi54** [comment]
@PierreBtz it looks good to me but I'm not sure how you would like me to test prior to something being deployed.

**Comment by diendanyoi54** [comment]
@PierreBtz it fails with `java.lang.ClassNotFoundException: com.damnhandy.uri.template.UriTemplate`. I thought it may be because you're missing TpeVoiceComment from the JsonSubTypes in the Comment class (and comment extension) but I added that and tested locally and it still fails with the same error.
```java
@JsonSubTypes({@Type(
    value = Comment.class,
    name = "Comment"
), @Type(
    value = VoiceComment.class,
    name = "VoiceComment"
)})
public class Comment implements Serializable {
```

**Comment by PierreBtz** [comment]
@diendanyoi54 thanks, I commented on the PR? I believe we can amend this one with:

```
@JsonTypeInfo(use = NAME, include = EXTERNAL_PROPERTY, property = "type", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = Comment.class, name = "Comment"),
  @JsonSubTypes.Type(value = VoiceComment.class, name = "VoiceComment"),
  @JsonSubTypes.Type(value = VoiceComment.class, name = "TpeVoiceComment")
})
public class Comment implements Serializable {
```
