### ISSUE TITLE
Couldn't authenticate you

### ISSUE THREAD

**Issue by 327078466** [cloudbees-oss/zendesk-java-client#695]
![image](https://github.com/cloudbees-oss/zendesk-java-client/assets/88604688/4766d59a-9717-420b-ab48-915e078b9d47)
 i promise this right  but why???

**Comment by 327078466** [comment]
![image](https://github.com/cloudbees-oss/zendesk-java-client/assets/88604688/997e680c-002d-4dce-acfb-47616d8db795)
why my username and password is right ? but Couldn't authenticate

**Comment by PierreBtz** [comment]
I'm sorry I can't debug an authentication issue for you.
To be honest with you, those methods have been working properly for years, it would be surprising if this was an error with the code.
You'll probably want to review https://support.zendesk.com/hc/en-us/articles/4408831452954-How-can-I-authenticate-API-requests#:~:text=To%20authenticate%20API%20requests%2C%20use,or%20URL%20are%20not%20processed. to spot the issue.
