### ISSUE TITLE
getSearchResults query containing "+" don't work

### ISSUE THREAD

**Issue by simonl2002** [cloudbees-oss/zendesk-java-client#72]
I am attempting to query users with a phone number. So using `getSearchResults` like so. 

``` java
client.getSearchResults(User.class, "phone:+16465551000");
```

I was testing queries with known numbers so I expected to get results but got none. I turned on debugging and it looks like the "+" is not being properly escaped. 

```
GET /api/v2/search.json?query=phone%3A+16465551000+type%3Auser
```

So you can see that the plus is not escaped. Also note the "+" between the number and `type`.

From my initial look at the code `+` is used to insert a space in the url. Is there a reason a space wasn't used which the underlying `com.damnhandy.uri.template.UriTemplate` would then properly escape? I have tried using UriTemplate directly and when it is passed "type:user phone:+16465551000" it does produce a properly escaped url.

**Comment by cbrunnkvist** [comment]
> I turned on debugging

Is there a way to "turn on" HTTP debugging? I'm using log4j in my project and have been trying to figure out how to get a request/response dump to look at.
