### ISSUE TITLE
Valid email address causes HTTP/422: Unprocessable Entity  

### ISSUE THREAD

**Issue by douglashanley** [cloudbees-oss/zendesk-java-client#93]
If the Requester object in a createTicket request has an email of the form john.i.doe@someplace.com it causes a validation exception on the server side which complains that the requester must have a non-zero length.  I guess it is one or more "." before the @ which is causing some parsing errors?

**Comment by fredley** [comment]
I am also getting this error:

    Ticket{assigneeId=null, id=null, url='null', externalId='null', type='null', subject='Test Feedback', description='null', priority='null', status='null', recipient='null', requesterId=null, submitterId=null, organizationId=null, groupId=null, collaboratorIds=null, forumTopicId=null, problemId=null, hasIncidents=false, dueAt=null, tags=null, via=null, customFields=null, satisfactionRating=null, sharingAgreementIds=null, followupIds=null, ticketFormId=null, brandId=null, createdAt=null, updatedAt=null}

with

    requester: Requester{localeId=null, name='test@mydomain.co.uk', email='Test Account'}

    comment: Comment{id=null, body='Hello, this is test feedback', authorId=null, attachments=null, createdAt=null, uploads=null}
