### ISSUE TITLE
Ticket#dueAt is serialised incorrectly

### ISSUE THREAD

**Issue by jon-ruckwood** [cloudbees-oss/zendesk-java-client#94]
When a Ticket is serialised it seems that `dueAt` is represented by a `long` instead of an ISO 8601 formatted String. This causes the API to reject the request.

Actual:

``` json
{"ticket":{"type":"task","has_incidents":false,"due_at":1420070462000}}
```

Expected:

``` json
{"ticket":{"type":"task","has_incidents":false,"due_at":"2015-01-01T00:01:02.000Z"}}
```

I fixed this in a fork (see: https://github.com/jon-ruckwood/zendesk-java-client/commit/3f112393f53a6e5a5f67d9a1b9b5d1b6b855623f), I'm not sure if that's useful at all.

**Comment by mttdbrd** [comment]
I just came across this too. There are several ways to fix it. I'm not sure that @jon-ruckwood's fix is the cleanest.  There are some easier ways documented here (including using annotation directives to Jackson): http://stackoverflow.com/a/31613581/3022173

**Comment by jon-ruckwood** [comment]
@mttdbrd +1 Yep it's cleaner fix. 

I was thinking that other Date fields across the model would need this serialisation applying also.

**Comment by aheritier** [comment]
This is the problem to use old Date Objects. they are serialized by default to the timestamp
Replacing all Dates by OffsetDateTime should be better but it's a big API change :(
Changing globally the option like  @jon-ruckwood did is a good option if all date fields are managed like this (it seems to be the same than #331) but we can locally do it on each date field with JsonFormat like proposed by @mttdbrd

**Comment by aheritier** [comment]
For now we have 

```
        mapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
        mapper.setDateFormat(new StdDateFormat());
```

**Comment by aheritier** [comment]
With #348 I cannot reproduce the issue in a test
