### ISSUE TITLE
Implementation of /api/v2/users/create_or_update_many.json

### ISSUE THREAD

**Issue by booshi** [cloudbees-oss/zendesk-java-client#96]
This API does not have the implementation of the /api/v2/users/create_or_update_many.json method.

Accepts an array of up to 100 user objects. For each user, the user is created if it does not already exist, or the existing user is updated. It is painful to send the request to /create_many.json, parse thru the response and update each user in the list who already existed.

**Comment by matthewtckr** [comment]
API Doc: https://developer.zendesk.com/rest_api/docs/core/users#create-or-update-many-users

**Comment by matthewtckr** [comment]
Sample implementation available in matthewtckr/zendesk-java-client@a18bf05f063872e59646902351d33710620f051b commit (no smoke test)

**Comment by ssteward54** [comment]
Are there any plans to support this functionality?
