### ISSUE TITLE
JobStatus related to createTickets doesn't seem to contain Ticket entities

### ISSUE THREAD

**Issue by jon-ruckwood** [cloudbees-oss/zendesk-java-client#98]
In the case of `Zendesk#createTickets` it doesn't seem like `JobStatus#results` contains `Ticket` entities.

Given I want to create multiple tickets, and one or more of those tickets contains a validation error:

``` java
JobStatus<Ticket> jobStatus = zendesk.createTickets(tickets);
```

When I receive the JobStatus (or perform further `Zendesk#getJobStatus`), the JSON received is:

``` json
{
    "job_status": {
        "id": "1",
        "url": "https://subdomain.zendesk.com/api/v2/job_statuses/1.json",
        "total": 1,
        "progress": 0,
        "status": "failed",
        "message": "Failed at 2016-01-15 10:39:18 +0000",
        "results": [{
            "index": 0,
            "error": "TicketCreateFailed",
            "details": "Description: cannot be blank"
        }]
    }
}
```

But it's deserialized as (toString representation):

``` java
JobStatus{
  id='1',
  url='https://subdomain.zendesk.com/api/v2/job_statuses/1.json',
  total=1,
  progress=0,
  status=failed,
  message='Failed at 2016-01-15 10:39:18 +0000',
  results=[
    Ticket{
      assigneeId=null,
      id=null,
      url='null',
      externalId='null',
      type='null',
      subject='null',
      description='null',
      /* other properties omitted */
    }
  ]
}
```

Even when all the tickets are created successfully, deserialization of the `JobStatus` may fail as the JSON `$.job_status.results.status` value can be `Updated` which doesn't map to a `Ticket#status` enum value, e.g.:

``` json
"results":[
 {
    "id":4,
    "title":"Test 2 - ignore",
    "action":"update",
    "status":"Updated",
    "success":true,
    "errors":""
}
```

will cause:

```
java.lang.IllegalArgumentException: Can not construct instance of org.zendesk.client.v2.model.Status from String value 'Updated': value not one of declared Enum instance names: [new, open, pending, hold, solved, closed, deleted]
```

I'm not sure what the answer to this would be but I just wanted to make other people aware of this potential problem.

**Comment by jon-ruckwood** [comment]
Also, I imagine this might be an issue for other API calls which return job statuses. (I noticed similar behaviour when attempting implementing the bulk update tickets endpoint).

**Comment by wakingrufus** [comment]
I have run into this same issue when trying to implement this endpoint in the java client: 
https://github.com/cloudbees/zendesk-java-client/issues/261

**Comment by aheritier** [comment]
Job Status aren't returning (at least as documented today) the objects in the result but a specific array of objects

https://developer.zendesk.com/rest_api/docs/support/job_statuses#json-format

Results
The "results" array in a response lists the resources that were successfully and unsuccessfully updated or created after processing.

The results differ depending on the type of job. If the job was to bulk create resources, each result specifies the following:

the id of the new resource ("id": 245)
the index number of the result ("index": 1)
If the job was to bulk update resources, each result specifies the following:

the id of the resource the job attempted to update ("id": 255)
the action the job attempted ("action": "update")
whether the action was successful or not ("success": true)
the status ("status": "Updated")

**Comment by aheritier** [comment]
For exemple if I create 5 tickets I receive:

```
{
  "job_status": {
    "id": "0b6b4324c35b14a5ff29690c7a213305",
    "url": "https://cloudbees1557872254.zendesk.com/api/v2/job_statuses/0b6b4324c35b14a5ff29690c7a213305.json",
    "total": 5,
    "progress": 5,
    "status": "completed",
    "message": "Completed at 2020-05-29 12:59:28 +0000",
    "results": [
      {
        "index": 0,
        "id": 2185,
        "account_id": 9281666
      },
      {
        "index": 1,
        "id": 2186,
        "account_id": 9281666
      },
      {
        "index": 2,
        "id": 2187,
        "account_id": 9281666
      },
      {
        "index": 3,
        "id": 2188,
        "account_id": 9281666
      },
      {
        "index": 4,
        "id": 2189,
        "account_id": 9281666
      }
    ]
  }
}
```

**Comment by aheritier** [comment]
The same when I create 2 organizations:

```
{
  "job_status": {
    "id": "dbb4608431bbdd96298542baba0642f4",
    "url": "https://cloudbees1557872254.zendesk.com/api/v2/job_statuses/dbb4608431bbdd96298542baba0642f4.json",
    "total": 2,
    "progress": 2,
    "status": "completed",
    "message": "Completed at 2020-05-29 13:07:08 +0000",
    "results": [
      {
        "id": 361078184892,
        "status": "Created"
      },
      {
        "id": 361078184912,
        "status": "Created"
      }
    ]
  }
}
```

The list of attributes varies too much I think to create different typed objects. The best is probably to use a List of Map

**Comment by aheritier** [comment]
and for a permanent ticket deletion. They are crazy at @zendesk 

https://developer.zendesk.com/rest_api/docs/support/tickets#delete-multiple-tickets-permanently

AH AH AH 

```
{
  "job_status": {
    "id": "b1d66f9f335537a9aec332b385e81620",
    "url": "https://cloudbees1557872254.zendesk.com/api/v2/job_statuses/b1d66f9f335537a9aec332b385e81620.json",
    "total": null,
    "progress": null,
    "status": "completed",
    "message": "Completed at 2020-05-29 17:24:44 +0000",
    "results": {
      "success": true
    }
  }
}
```
